### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by hoshsadiq** [rfc2822/GfxTablet#16]
It would be cool to create Windows driver for this.

**Comment by Nesh108** [comment]
Hey @hoshsadiq,

Some time ago I was a bit bored and I wrote a quick hack for Windows. It worked for me and some other people, give it a try if you feel like: https://github.com/Nesh108/GfxTablet_WindowsDriver

**Comment by blackcrack** [comment]
would be nice if you post the url from the compiled  :)

best regards
Blacky

**Comment by Nesh108** [comment]
Here you go: https://github.com/Nesh108/GfxTablet_WindowsDriver/blob/master/GfxTablet_WindowsDriver-v1.1.exe

**Comment by blackcrack** [comment]
thank you :)
