### ISSUE TITLE
What am I doing wrong in trying to open port 40118 (UDP)?

### ISSUE THREAD

**Issue by colinkeenan** [rfc2822/GfxTablet#57]
I have done the following:
1) installed https://aur.archlinux.org/packages/gfxtablet-git/ which gives me the networktablet server for my Arch linux computer. 
2) installed Gfx Tablet from the Google Play Store on my 2012 Nexus 7
3) entered my computer's host name (colin). 
4) sudo networktablet
5) opened new image in Gimp, choosing pencil and putting it over the image ready to draw.
6) drew on the app. Nothing happened.
7) went to 192.168.1.1 to access advanced settings on my Google Fiber router.
8) created a user-defined application for port forwarding: 192.168.1.7 networktablet - UDP 40118 -> 40118. Where, 192.168.1.7 is the location of my computer 'colin'.
9) restarted networktablet and the app, and Gimp.
10) still can't draw into Gimp from my Nexus 7.

What am I doing wrong? I have no way to completely disable the firewall provided by Google Fiber.

OK - NEVERMIND: I decided to go back into Gfx Tablet and enter 192.168.1.7 instead of 'colin'. That worked! Also, I decided to see what happened if I deleted the port forwarding rule. It still works! You don't need port forwarding when both devices are on the same network.

Your Gfx Tablet app should complain if it can't find the host so that I know I have to enter something else there.

I will keep all this here in case it helps anyone, but I also have another question. 

Why do I have to run networktablet as root?

Is it possible in the future we can see the desktop on the tablet itself so we know where to touch the screen after lifting our finger?

**Comment by rfc2822** [comment]
> Why do I have to run networktablet as root?

You don't have to. The driver runs in user-mode, so it doesn't need any special privileges. However, it needs access to /dev/uinput. If your distribution doesn't create a group for uinput access, you'll need to do it yourself or just run the driver as root:

> Is it possible in the future we can see the desktop on the tablet itself so we know where to touch the screen after lifting our finger?

Of course, that would be the killer feature. However, at the moment GfxTablet is only an _input_ device and not a virtual screen. Implementing this would go far beyond the scope and possibilities of the current GfxTablet project.
