### ISSUE TITLE
Step-by-step

### ISSUE THREAD

**Issue by DanN7** [rfc2822/GfxTablet#70]
Sorry but..
Can you provide the step-by-step tutorial video for How to install it, how to configure it, until it can used on the smartphones?
I have already tried but always get IP 0.0.0.0. Really confused..
I use Ubuntu 13.10 + Nexus 5
Thanks..

**Comment by jeffshaw-dev** [comment]
hello, I made a video of setting up GfxTable. Hope this helps.
https://youtu.be/6PUqWY-YQmw
