### ISSUE TITLE
Disable hardware buttons / enable screen rotation

### ISSUE THREAD

**Issue by ayberkozgur** [rfc2822/GfxTablet#78]
There should be an option to disable hardware buttons as the hand tends to accidentally touch them during normal use:
![img_20150115_100538](https://cloud.githubusercontent.com/assets/1974284/5755019/058078b6-9ca0-11e4-95e3-389b3c4ec26b.jpg)

This for example causes the app to quit since the back button was touched accidentally. This can be worked around if the portrait orientation is forced but rotation is not disabled so that the device can be used upside down like this:
![img_20150115_100613](https://cloud.githubusercontent.com/assets/1974284/5755032/347d0cce-9ca0-11e4-9b9c-3580d4df38a5.jpg)

Also in this case, the top system bar should be disabled (somehow, I don't know if it's doable) because it tends to be dragged down by accident.

**Comment by FatihBAKIR** [comment]
I dont think you can disable the home button entirely, but back button can easily be disabled, I implemented that in my fork: https://github.com/FatihBAKIR/GfxTablet

**Comment by ayberkozgur** [comment]
I have the exact same in my fork :) https://github.com/ayberkozgur/GfxTablet/commit/63937c7866976c10da2ab4dba382c19e0c58793d

**Comment by rfc2822** [comment]
Hardware buttons are now disabled using "sticky immersive mode" on Android 4.4+ when you enter full-screen mode in GfxTablet.
