### ISSUE TITLE
How do i check if my android has successfully connected ?

### ISSUE THREAD

**Issue by flouthoc** [rfc2822/GfxTablet#79]
When i start ./networktablet it shows "GfxTablet driver (protocol version 1) is ready and listening on 0.0.0.0:40118 (UDP)" and now i enter my system's local IP address into android's Host Promt,
but both of my system and android shows no notification about successfull connection is it working fine ?

**Comment by GeorgeGkas** [comment]
yes, probably. There isn't any functionality such as that you described but it will be a good update. Start Gimp->Edit->Input Devices and check for Network tablet. If there exist such option in your left hand window then click it and set the Mode to Screen. then touch your tablet screen and see the magic! If there's no option about Network tablet in Input Devices window then somenthing went wrong. Don't forget to check your ip of wlan to set the Settings in your App correctly. Check that and tell us if all working!

**Comment by flouthoc** [comment]
@GeorgeGkas well i've solved it ! i forgot to close this issue :smile:
