### ISSUE TITLE
error: prepare_socket(): Address already in use

### ISSUE THREAD

**Issue by Bhav97** [rfc2822/GfxTablet#85]
![screenshot from 2015-06-14 19 52 28](https://cloud.githubusercontent.com/assets/12880701/8148918/35e8b16c-12cf-11e5-9808-5415148b50b2.png)
![screenshot from 2015-06-14 19 52 51](https://cloud.githubusercontent.com/assets/12880701/8148919/35eef1c6-12cf-11e5-85d4-252c70ab29dd.png)
![screenshot from 2015-06-14 19 55 18](https://cloud.githubusercontent.com/assets/12880701/8148922/4e1e5ed0-12cf-11e5-84b5-6b61feed2039.png)

Need help

**Comment by rfc2822** [comment]
This means that `networktablet` (or another app using the same port) is already running. You can see a list of running applications and their UDP ports with `sudo netstat -an | grep udp`.
